### ISSUE TITLE
load_toml_app_config has no clear preference if more configs are found

### ISSUE THREAD

**Issue by hroncok** [mcurlej/joft#37]
In this code:

https://github.com/mcurlej/joft/blob/70eac8517b375bea51bbdabe01b007c971054944/joft/utils.py#L18-L26

`possible_paths` is a set.

That means if multiple config files are found, an arbitrary one is selected. Each time a different one:

```
$ python -c 'print(list({"/etc", "/home/churchyard/.config", "."})[0])'
/etc
$ python -c 'print(list({"/etc", "/home/churchyard/.config", "."})[0])'
.
$ python -c 'print(list({"/etc", "/home/churchyard/.config", "."})[0])'
/etc
$ python -c 'print(list({"/etc", "/home/churchyard/.config", "."})[0])'
/etc
$ python -c 'print(list({"/etc", "/home/churchyard/.config", "."})[0])'
/home/churchyard/.config
```

Instead, the config file locations should have a clear defined preference. For example, the one in PWD should always be preferred over the one in HOME config, which should be preferred over the one in /etc.

**Comment by frenzymadness** [comment]
Feel free to open a PR.
