### ISSUE TITLE
site_config_dir is added split to each character

### ISSUE THREAD

**Issue by hroncok** [mcurlej/joft#38]
https://github.com/mcurlej/joft/blob/70eac8517b375bea51bbdabe01b007c971054944/joft/utils.py#L22

This adds each letter separately:

```pycon
>>> import platformdirs
>>> possible_paths = set()
>>> possible_paths.add(platformdirs.user_config_dir())
>>> possible_paths.update(*platformdirs.site_config_dir(multipath=True).split(":")) 
>>> possible_paths
{'g', 'x', '/home/churchyard/.config', 'e', '/', 't', 'c', 'd'}
```

set.update takes one or more iterables to add from one by one, not individual items to add. The `*` is unnecessary.

**Comment by frenzymadness** [comment]
This was already fixed today in https://github.com/mcurlej/joft/pull/35
