### ISSUE TITLE
Config file validation

### ISSUE THREAD

**Issue by frenzymadness** [mcurlej/joft#40]
It seems that we have to create an empty config file and ship it via RPM. That means that we need to validate the content of config files and raise a meaningful error if we find an invalid one.

**Comment by hroncok** [comment]
> It seems that we have to create an empty config file and ship it via RPM.

That was a misunderstanding, see https://bugzilla.redhat.com/show_bug.cgi?id=2318507#c6

> That means that we need to validate the content of config files and raise a meaningful error if we find an invalid one.

But this is correct anyway.
