### ISSUE TITLE
Add a CLI option which will display a list of issues found by the JQL query

### ISSUE THREAD

**Issue by mcurlej** [mcurlej/joft#5]
Something like `PROJECT-123 (<url to the issue on your jira instance>)`

**Comment by mcurlej** [comment]
We could also additional information which will show preview of fields which you want to create/change in the specific issue. This could also check if any `${...}` references in the `fields` section are still unresolved and warn the user. The could run also before a real run in the background to check for unresolved `${...}` references in the `fields` section.

**Comment by frenzymadness** [comment]
There is a PR already for the list-issues command #17

**Comment by frenzymadness** [comment]
The new command is there already. If you want to implement anything more, open a new issue, please.
